openapi: 3.0.0
info:
  title: Express API with Swagger
  version: 1.0.0
paths:
  /health:
    get:
      summary: Get the root endpoint
      responses:
        '200':
          description: Successful response
